### ISSUE TITLE
OSLC Automation v3.0 PSD 01 publication

### ISSUE THREAD

**Issue by berezovskyi** [oasis-open-projects/administration#17]
*Requester name:* Andrew Berezovskyi

*OP name:*  OSLC OP

*OP email address:* oslc-op@lists.oasis-open-projects.org 

*Title:* OSLC Automation v3.0 PSD 01

*Request link:* 
https://lists.oasis-open-projects.org/g/oslc-op/topic/intent_to_publish_oslc/78714754?p=,,,50,0,0,0::recentpostdate%2Fsticky,,,50,2,0,78714754

*Notes:*
PGB will hold a vote on the last meeting of the year on Dec 17. Please check the package for OASIS rule conformance in parallel to enable publication with minimal delays.

**Comment by paul-knight** [comment]
Initial review:

Initial review of material:

I assume that the following items will be addressed as usual in preparing the files after approval, but I am listing them for completeness:
- need appropriate labels for "Project Specification Draft 01" (subtitle, and in "Citation format")
- need URIs for This stage, Previous stage, Latest stage.
- need approval date (subtitle and in "Citation format"). (Also, copyright year 2021 for "Notices")

Part 1: Specification - comments:
- remove the "IPR Policy" section (1.1) and renumber following sections.

Best practice update: for RFC Terms

OSLC-OP should update the "Typographical Conventions and Use of RFC Terms" sections to use the current IETF format, which includes another RFC (8174) and reference to the specific BCP 14, along with the traditional 2119. It also adds "NOT RECOMMENDED" to the terms list. This should also be applied for other future OSLC-OP publications.

- Text:
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here.

- Citations:
[RFC2119]
Bradner, S., "Key words for use in RFCs to Indicate Requirement Levels", BCP 14, RFC 2119, DOI 10.17487/RFC2119, March 1997, <http://www.rfc-editor.org/info/rfc2119>.

[RFC8174]
Leiba, B., "Ambiguity of Uppercase vs Lowercase in RFC 2119 Key Words", BCP 14, RFC 8174, DOI 10.17487/RFC8174, May 2017, <http://www.rfc-editor.org/info/rfc8174>.

**Comment by jamsden** [comment]
I will make these changes and provide a new zip file.

**Comment by berezovskyi** [comment]
For the record, the ballot was closed successfully: https://lists.oasis-open-projects.org/g/oslc-op-pgb/topic/oslc_automation_2_1_psd_01/79625278?p=,,,50,0,0,0::recentpostdate%2Fsticky,,,50,2,0,79625278

**Comment by jamsden** [comment]
Paul, the updates have been completed and are in https://github.com/oslc-op/oslc-specs/releases/download/untagged-7a1158b4039db64c1418/auto-v2.1-psd01.zip

**Comment by paul-knight** [comment]
Initial review - looks good. I may also be able update the logo on the front pages (to use the new OASIS logo)...

**Comment by berezovskyi** [comment]
Best if changes are made to the source and not the generated output:

- https://github.com/oslc-op/oslc-specs/blob/master/specs/auto/automation-spec.html
- https://github.com/oasis-tcs/tab-respec/blob/master/js/templates/headers.html

**Comment by paul-knight** [comment]
Since the logo is linked from the OASIS website (https://docs.oasis-open-projects.org/templates/logo/open-projects-logo.png), I should be able to just replace that file, with no adjustment to the source.

However, I don't think we have a replacement logo/banner file in hand now, so for now we'll probably stick with the current one for this publication.

**Comment by paul-knight** [comment]
Files prepared and staged for initial internal review. No changes have been made. Nice work!
Should be published soon.

**Comment by paul-knight** [comment]
Noted broken (not yet instantiated) links in all Parts for:
Latest version:
    https://open-services.net/spec/auto/latest
Latest editor's draft:
    https://open-services.net/spec/auto/latest-draft

These will depend on the OSLC team setting things up on open-services.net, so I will not delay publication just for this.

Other minor items noted:
- the two .ttl files show "Copyright 2020" - time to update!
- the hyperlink for Koneksys (Editor Fabio Ribeiro) should use http: instead of https:, since it triggers error/warning messages using https.  (appears in all Parts)
- in automation-spec, there are three line rules before Section 9, instead of one. This results in two blank pages in the PDF.

Apparent bad links in automation-spec:
- Normative Reference [OSLCActions] links (2) return 404 errors
- Link to " OSLC Actions 2.0 specification" in top line of Section 5 is broken.
- Four links (two each in Sections 8.1 and 8.2) are broken. They point to non-existent documents like http://docs.oasis-open.org/oslc-domains/oslc-auto/v2.1/csprd01/part2-automation/oslc-auto-v2.1-csprd01-part2-automation-vocab.html#AutomationRequest - Note that the Work Product "oslc-auto" was never published under http://docs.oasis-open.org/oslc-domains/.
- 
We are proceeding with the release of this first published draft for OSLC Automation.

**Comment by paul-knight** [comment]
Running final checks on the files before announcing to the entire OP email list... ready for review by the OP Editors if desired.

The files are:

OSLC Automation Version 2.1
Project Specification Draft 01
21 January 2021

OSLC Automation Version 2.1. Part 1: Specification
https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-spec.html
https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-spec.pdf
OSLC Automation Version 2.1. Part 2: Vocabulary
https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-vocab.html
https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-vocab.pdf
OSLC Automation Version 2.1. Part 3: Constraints
https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-shapes.html
https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-shapes.pdf
Change Management Vocabulary definitions file: https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-vocab.ttl
Change Management Resource Shape Constraints definitions file: https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-shapes.ttl

Please let us know if you notice any issues we should address.

**Comment by jamsden** [comment]
Looks good.-----Paul Knight <notifications@github.com> wrote: -----To: oasis-open-projects/administration <administration@noreply.github.com>From: Paul Knight <notifications@github.com>Date: 02/08/2021 07:20PMCc: Jim Amsden <jamsden@us.ibm.com>, Comment <comment@noreply.github.com>Subject: [EXTERNAL] Re: [oasis-open-projects/administration] OSLC Automation v3.0 PSD 01 publication (#17)Running final checks on the files before announcing to the entire OP email list... ready for review by the OP Editors if desired.The files are:OSLC Automation Version 2.1Project Specification Draft 0121 January 2021OSLC Automation Version 2.1. Part 1: Specificationhttps://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-spec.htmlhttps://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-spec.pdfOSLC Automation Version 2.1. Part 2: Vocabularyhttps://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-vocab.htmlhttps://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-vocab.pdfOSLC Automation Version 2.1. Part 3: Constraintshttps://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-shapes.htmlhttps://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-shapes.pdfChange Management Vocabulary definitions file: https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-vocab.ttlChange Management Resource Shape Constraints definitions file: https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-shapes.ttlPlease let us know if you notice any issues we should address.

**Comment by berezovskyi** [comment]
> Latest version:
> https://open-services.net/spec/auto/latest
> Latest editor's draft:
> https://open-services.net/spec/auto/latest-draft

Redirects have been set up

**Comment by berezovskyi** [comment]
I think we can close this one. Thanks @paul-knight for your kind help getting the spec published!

**Comment by paul-knight** [comment]
Sent separate message to OSLC-OP mail list:
- https://lists.oasis-open-projects.org/g/oslc-op/message/453
Yep, should be all done here.

**Comment by berezovskyi** [comment]
🙏
