### ISSUE TITLE
[SMV] Hold Special Majority Vote to approve OSLC Query Version 3.0 Project Specification 01 as a Candidate for OASIS Standard

### ISSUE THREAD

**Issue by berezovskyi** [oasis-open-projects/administration#23]
*Requester name:* Andrew Berezovskyi	

*OP name:* OSLC OP

*OP mailing **address:*** oslc-op@lists.oasis-open-projects.org

*Title:* OSLC Query Version 3.0 Candidate for OASIS Standard (Project Specification 01)

*Approval link:* 
https://lists.oasis-open-projects.org/g/oslc-op/message/364

*Statements of Use:*

1. https://lists.oasis-open-projects.org/g/oslc-op/message/519
1. https://lists.oasis-open-projects.org/g/oslc-op/message/529
1. https://lists.oasis-open-projects.org/g/oslc-op/message/567

**Comment by chet-ensign** [comment]
TC Admin JIRA ticket https://issues.oasis-open.org/browse/TCADMIN-3998 was opened to track this work.

**Comment by chet-ensign** [comment]
Setting up the ballot now.

**Comment by chet-ensign** [comment]
The ballot is set up. Both Core and Query are listed under the same topic but they are individual ballots. This ballot is at https://lists.oasis-open-projects.org/g/oslc-op-pgb/message/151 and also closes on June 8th. 

I will close this ticket.
