### ISSUE TITLE
Publish OSLC Link Discovery Management Version 1.0 PSD01

### ISSUE THREAD

**Issue by jamsden** [oasis-open-projects/administration#24]
*Requester name:* Jim Amsden

*OP name:*  OSLC-OP

*OP email address:* oslc-op@lists.oasis-open-projects.org 

*Title:* OSLC Link Discovery Management Version 1.0. Part 1: Specification

*Request link:* https://github.com/oslc-op/oslc-specs/releases/edit/untagged-c030429ecb2bb35c26a0

*Notes:* ldm-v1.0-psd01.zip is in the request link and attached here.
[ldm-v1.0-psd01.zip](https://github.com/oasis-open-projects/administration/files/13813462/ldm-v1.0-psd01.zip)

**Comment by OASIS-OP-Admin** [comment]
Issue has been transferred to https://issues.oasis-open.org/browse/TCADMIN-4461. I will close this copy.
